//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location_Type()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int Location_Type_id { get; set; }
        public string Location_Type_Name { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
