//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Query()
        {
            this.Technicals = new HashSet<Technical>();
        }
    
        public int Query_id { get; set; }
        public string Query_Description { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Location_id { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Status { get; set; }
        public string Created_by { get; set; }
        public string Assign_To { get; set; }
        public string Assign_By { get; set; }
        public string Query_Type { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technical> Technicals { get; set; }
    }
}
