//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technical
    {
        public int Technical_id { get; set; }
        public Nullable<int> Query_id { get; set; }
        public string Problem_Finding { get; set; }
        public string Action_Taken { get; set; }
        public string Comments { get; set; }
        public string Reason_for_Transfer { get; set; }
        public Nullable<System.DateTime> Dated_Fixed { get; set; }
        public string Fixed_By { get; set; }
    
        public virtual Query Query { get; set; }
    }
}
